-- Base entity columns are handled in all tables
CREATE TABLE IF NOT EXISTS property_promotion_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id INTEGER NOT NULL,
    promotion_id INTEGER NOT NULL,
    price_factor DECIMAL(5,2) DEFAULT 1.0 NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
); 